{% set name = "ansible" %}
{% set version = "2.10.5" %}
{% set base_version = "2.10.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9775229aae31336a624ca5afe5533fea5e49ef4daa96a96791dd9871b2d8b8d1
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-base/{{ name }}-base-{{ base_version }}.tar.gz
    sha256: d4dad569864c08d8efb6ad99acf48ec46d7d118f8ced64f1185f8eac2c280ec3
    folder: base

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - paramiko
    - jinja2
    - pyyaml
    - httplib2
    - cryptography
    - six
    - openstacksdk
    - boto

test:
  commands:
    - ansible --version
  imports:
    - ansible
    - ansible.constants
    - ansible.errors
    - ansible.utils

about:
  home: http://github.com/ansible/ansible
  license: GPL-3.0-only
  license_file: COPYING
  summary: Ansible is a radically simple IT automation platform

  description: |
    Ansible is a radically simple IT automation platform
    that makes your applications and systems easier to deploy.
    Includes support for OpenStack (shade) and EC2 (AWS), extra
    batteries included.
  doc_url: https://www.ansible.com/
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - brainstorm
    - tschoonj
