# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EJQGbVJh9BLtQIzPmE4rN5x0UIG+AE9aNaHr3OXUvWgh0Mr/IxL6OtI0JC/k6TlNx9GCaCh827GFoY7IKN15XwpPszwIxt4KuAZ1kUAtY7kWmAxhDVRfboOh+tLul46ig238wtT3tBjJIB9+RQwVfG60l7sts/73AAmGcXPJMk1hNx9WnZutuKPCPq+NOXZou5RZzmpB0R5vY3QoyCa92jJrWjF8IZG+de0j/Ky3pfQW3QhwEN/eiMuNBKEON2HpXO/BvPysJyU66tFBrk8l/UpKSKud2Vl/ouIXWBLvJfqtTQs06wz1b0vQasRkEJyw//qVuy8Zv7xDIRv+H7YNVQ+kxarTa5TdteOL23BfM3lfrN2OG3qn1e2jz32p0CTO4J1ixLj7w0kInRDcpMkrzB1Q1TvetiThh50wy5EwYkfkwU6pn8/fACCYUFy1pN+6GW3UYgCMml7fAKw7ld20t1+90MtdnLQ1uMSKYWS6WDeqsLawVZninUUXTptGn+hvG0a0ftAqMvZ1SvcpfQym7WjjCvIa3FarwBRobcoZMwYW9wFsW9fCpBZnIJS8yyTNLEr2cfgZmRn/EtYLN5+2tLxybgBoZ6Uws/UzvLc3CfxLQBEC1KKm3dXRBdcs+oI3vwJ3DLCRzESPQPVbb/awQduw+hN92pnTjI3dsxz889I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
