travis:
  secure:
    BINSTAR_TOKEN: mXuEza+mo4wFL2wKPrunL2S/DnetgtTUz05Z/fAzqvU+a69uKwOgvkmadi4SsGQ0p6uzrbepYSv80w04aiNvxiT0FGYJWrWmrVy1M16GpwaoOrI3muobJ07WYJRmCjtQDJa0/LQH++wZCjiaFVuFPNqChFBuypzR1TzstOdck8xGMod6LgQm7YMzTGABTpPpsKnEa14jCi6R5LXpTbeBcsc6E6mhcssTjtY+CPH7TCZ/MtYEmEcJbdmzXrUw0mbzBJ05Lwbq55uvGdTyMyIpIGMq9tfnZC6Gar036Z7VxU+YsKY9wKpI543K3ltcosgJKVPGBR2VV/PVE3PKY51/YbrRbaPCNWSyPGXQwpDvDTk69Rjm9CiXjoZmPvPadt0Bl12zlNfaiZFAN70ptlELxFfB1+dAX7AG9LEmISrGzu4TyArE9/tYXXl7jJ+LbgxqSS3jmE37oBjVhBCYRenIIGNazI/0b+uuDuZ2InDpcV3KwE8PiC0jUxZuIlINYUQjuk2f8kSNgbMoAGuy1KuG+8wiaWMt+Q/rt+npo8yeCJDWnjv902x3ztUE2g/Miw5RWkIvS3E5ngccg+bhTlW79WCjZyv4i/ajG2cEM1YV/rV1qE4dsELB4kvYLqawy2U6C6hqR/wYMOHiu8nNwctW9AvZEAUKXWgRmUIwAWknaW8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
