travis:
  secure:
    BINSTAR_TOKEN: TBhDsadCbdxipp8kvYcFS3qqAyrFHC+OZI6FAp3r1MlF+yH5FAeGk0+b1JeKd9H1cCSOAVskR+dAqEdSQE7zRuXg8/b0LGgmhrFRHSzqgbBMf8cQUU53bzi/7uPewIAnY/CMpgfGb4DqI4q1JbwuLfhZ+wnT3CqMxlES9J5pDEtPkl7Qu8YJ74TDqdwbVH2aLYUAZYyc3K8U8GR1sD5QtfNFWx5uiuiA/j637bUqVg2jbBHEIjRR8UrVg4u6vYQ+NtAhB6kn74+0FwzO2Cf7Xf5pf5thOHVVZ9aKTvyWLTH5Bu7sOm/W5L3bVjEq8FHEe9JTDiyGsZm9YTv5SBIoWFYLx8qTz+FCeRQE82Z5ghxD1L4sWgP5nzIRrdQozdLkFlhdpsO1G3cAaNqe66SFXQJAeWWAv6+C/TUtqyRGpe2WeQleDvQrz0J4vKaH3fLPERrhScoX97zElab4A7iAiQ4p6JA6HnaFNXINhIezisiM1h/ldCwxm6wvk87pJDme2djq+B8EhlpsT3IEUxBoX3Y3zVQ5ECImOhf+zPID7fI8EObQgXQmIoZHcCPmFP6koIl8IYoJCA9nKa8UBuOJA38wGaoDKMIzaztManFYW6eltv0BMXb5DxXTSQ47BgWHYY0tOXEbZmVZyYzRGbZ5Rx9YhvpdNVTgSzqOP7KHyhU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
