travis:
  secure:
    BINSTAR_TOKEN: EJQGbVJh9BLtQIzPmE4rN5x0UIG+AE9aNaHr3OXUvWgh0Mr/IxL6OtI0JC/k6TlNx9GCaCh827GFoY7IKN15XwpPszwIxt4KuAZ1kUAtY7kWmAxhDVRfboOh+tLul46ig238wtT3tBjJIB9+RQwVfG60l7sts/73AAmGcXPJMk1hNx9WnZutuKPCPq+NOXZou5RZzmpB0R5vY3QoyCa92jJrWjF8IZG+de0j/Ky3pfQW3QhwEN/eiMuNBKEON2HpXO/BvPysJyU66tFBrk8l/UpKSKud2Vl/ouIXWBLvJfqtTQs06wz1b0vQasRkEJyw//qVuy8Zv7xDIRv+H7YNVQ+kxarTa5TdteOL23BfM3lfrN2OG3qn1e2jz32p0CTO4J1ixLj7w0kInRDcpMkrzB1Q1TvetiThh50wy5EwYkfkwU6pn8/fACCYUFy1pN+6GW3UYgCMml7fAKw7ld20t1+90MtdnLQ1uMSKYWS6WDeqsLawVZninUUXTptGn+hvG0a0ftAqMvZ1SvcpfQym7WjjCvIa3FarwBRobcoZMwYW9wFsW9fCpBZnIJS8yyTNLEr2cfgZmRn/EtYLN5+2tLxybgBoZ6Uws/UzvLc3CfxLQBEC1KKm3dXRBdcs+oI3vwJ3DLCRzESPQPVbb/awQduw+hN92pnTjI3dsxz889I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
