travis:
  secure:
    BINSTAR_TOKEN: lKXdhYQcpNBx2AMrG4lw3i1J4UjLDTxZr0D9OENU+6YYNSR4p2tlSe13ud9AaBNmOOfTm1r4etm9h4Xy3JjbPZOoyP9oP645EPXnuP5Im1MrC/l4sPvj8sQZ4cvkZLVHzksLNLtpEPs762SmagTICSfL0MpBS1/ma6Sqn2d5Fj5ZATMRo9qXJ/0WPi3FHnLiUuYq+HBKOem4NfSNipAkQAn77LLIkxbS9eeZum9g2+I9+2nUDD/1hmp9JplejtSZfGAr4gJbm7bOOXcWfY64H+U+W5h/RPiPF9Re+dKlnOoIYQFc6iHU8Dl18e7PI9svl65q99fDV9ICRrUjE2KSy2gi+2YlXo54nOx70pDAEd9ZpvZY+jCqVUoiAAYor0UFJLa1ZNAo/pHr3/iM0CGpjXljqWSnMA/jb3X7g9TzHp/yQdEb0sBN6cDzt4zPrUcUkaYJ4E8qT05bgaUMWWw9iTvqn/BAuOC+r5r9VaUuaPwFqpMGJkF4uqSrSPE4O4tkD3DD9GawetVQahQnSz0bqqw8JDGt/KeSMiRg/tRuwB8WBUSShq9GYF+fdN7b38tgV4IY1zwg9N/I0RBHIBqclznuJPF1vuC7CXtRBPjzzZkgwTRd6XjCQzPUeDLrLYCnRsU1TDqAqEOCVnzh6te4l/ayjVCM/9GU4IGi3zuCGV0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
