travis:
  secure:
    BINSTAR_TOKEN: Jr6wYyZZPP18TE82hm1+JA06e4+rgW2h3qPBgOy9FTaqFYdN920V37g+TlHP12yt84uhJhY8Ulh3DqqtF8PLknFyLqfadwtvE01/DfqG2+V69ugYMuw2+Afa501YNJTGsZkRoRoo92JXwu9asAYFXNrLEn/hOhKURmt56I10ULXJZot9RMpJl7ME9t38dzwukBWr+vAvtbTmTvudLANgXbs1pV8pbdr99je4PNP8Ff5kR5X2ybm2/FzAgonRkTshKRhnLz694JSZdph/1aWA0P+khIIZrLDG+6FiD68/CN974m1KVot8HL6sBCpnsRUklpXsXg0H4SY/qm8/Vt1QcWex66S0W3/Vt/4hopkmdkwPTZVO0yCKsBgNTIi/60eBYy86goyLG/Zxa0qMmCzw1Mg7gvwcykZ/LsIW4DLVGFxFQDdsQ/qQYbhQ4oKsVZm1m0QF7VKCi1Ms7Sb1Egv9wM6oIHjM0abIBQ9+Oz0zApAKgn46uNPRRxUYQcwx8uyPZl4QLDoNvmCy5wP4PQVhhEAHGkGf4JsJlpIdmOzPaA+rPbfPCBUMsp1ruuTDaEwPqDdCKEmaAgMorerClrePDMSbY9Kwnlol8he/clRTDjnxu6noBRPC9iL4YhaWG/mjrzTMYFa8A+EYqfWIc8nT+lHL521PwnUYx4B/NXuWpMA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
