travis:
  secure:
    BINSTAR_TOKEN: j1z4FNKctoBTWo1Hln4yr+Zw5ogGNmpfOQvBSg04xjxCGLC91Rk18T5fD6qQQdUEhzYKS3KgBjypT0pycq/wtuphDJPpBJO/gne3hkv5mhHYrLpGQN4zpTDDSQCUmzTnaLFUCtGYGMTztS7r5YN8zjJkDgPDaox/GJUkKqfphy93/6sBTyf5tsmf17N30fiXjq3TQrr9AgKsi/118Df2dgTokgBxU/pGgviHB5pHc7ERpj28tfqtLVQ6vBZOV/qMwIHJ0X/dKZpxkBqb+dMEOnWunkXKQSya/ogFpbOkWWkP28eC56kjNMO6BfL3D+Iz+Cy9CSxooJm9Aq6YKRWMZV5AOlwcg291I6R/BLMpFg5+0yJo7dOl8qLJNnKn/U+OVABPJ7UKCurkEOEeCtoCraTrjDz7xN6K0VueQ81VTg/Ff1IEFmtjKVodtkzzJ7b6OU/Dhi62UOwv0BL834S34WGzUw4ZCspxGbTlFIF2afVl1b1TT3QkcMOQfLTjJ+uiPoMhdxeg/KUAkgrhoouQ6fqTFNB64h0IYmO+jEJSAwkg4wgTcAjv9Rdkludj4Wm6D87wzUz280JRLa/iw/iZw9IBhtK1m9T7HA8+f75iOaZci/F8tUWUWMH/ibcaErSP9ECkFQMz0Iukhz6klKlYYIzivrVpQdtrexovU/XTftw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
